/**
 * The livery's logo textures, generated by scripts/build-livery-decals.mjs from the BadCodes artwork:
 * do not edit by hand. `aspect` is width over height of the file, margins included.
 */
export const DECALS = {
  mark: { url: "/models/bc-mark.ab46fef6.png", width: 512, height: 383, aspect: 1.3368 },
  wordmark: { url: "/models/bc-wordmark.60b2e694.png", width: 1024, height: 174, aspect: 5.8851 },
} as const;
