/**
 * Where the wind tunnel's car sits in the Formula F226's frame (src/models/f1/car-frame.ts). Generated by
 * scripts/measure-tunnel-frame.mjs from public/models/f1-2026.1d32fb13.glb and public/models/f226.f3ba7133.glb: do not
 * edit by hand, rerun the script after `npm run models` or `npm run car`.
 *
 * A point of the tunnel car, (x, y, z) in its rest pose in metres, is at
 * (scale[0] * x + offset[0], scale[1] * y + offset[1], scale[2] * z + offset[2]) in the F226's frame, which is
 * the frame the livery rules are written in. The fit is over the bodywork and wings (trimmed chamfer
 * distance); `residualCm` is the tunnel car's own distance from the F226's painted surfaces after the map.
 */
export const TUNNEL_FRAME = {
  model: "f1-2026.1d32fb13.glb",
  reference: "f226.f3ba7133.glb",
  scale: [1.0165, 0.9902, 0.9879],
  offset: [-0.0402, 0.035, 0],
  residualCm: {
    mean: 3.09,
    p90: 6.17
  }
} as const;
